#!/bin/sh

PATH=$PATH:/home/abdul/.local/bin:/usr/sbin:/home/abdul/go/bin
. /home/abdul/.cargo/env

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
xrandr --output HDMI-1 --primary --mode 1920x1080 --output eDP-1 --off

bspc config border_width 3
bspc config window_gaps 12

bspc config focus_follows_pointer true
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color "#C678DD"
bspc config normal_border_color "#ABB2BF"
bspc config active_border_color "#61AFEF"
bspc config presel_feedback_color "#98C379"

xrdb --load ~/.Xresources

pgrep -x picom    > /dev/null || picom -f -i 0.8 --vsync &
pgrep -x dunst    > /dev/null || dunst &
pgrep -x sxhkd    > /dev/null || sxhkd &
pgrep -x xss-lock > /dev/null || xss-lock slock &
pgrep -x btops    > /dev/null || btops &

xidle -program slock -timeout 300 &
xidle -program "systemctl suspend" -timeout 600 &

feh --bg-fill ~/.local/share/background.jpg
xsetroot --cursor-name left_ptr
xset r rate 200 50
